version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: volteras
      POSTGRES_USER: volterasuser
      POSTGRES_PASSWORD: volteraspw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend_project.settings
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=volteras
      - DB_USER=volterasuser
      - DB_PASSWORD=volteraspw
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata: 