# Generated by Django 5.2.1 on 2025-05-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(db_index=True, max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('odometer', models.FloatField()),
                ('soc', models.IntegerField()),
                ('elevation', models.FloatField()),
                ('shift_state', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
