name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Build backend Docker image
        run: docker build -f Dockerfile.backend -t backend:latest .
      - name: Run backend tests
        run: |
          docker run --rm backend:latest python manage.py test || true
      - name: Login to DockerHub
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push backend image
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
        run: docker tag backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest && docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Build frontend Docker image
        run: docker build -f Dockerfile.frontend -t frontend:latest .
      - name: Run frontend build
        run: docker run --rm frontend:latest npm run build
      - name: Login to DockerHub
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Push frontend image
        if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
        run: docker tag frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest && docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest 