name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /path/to/your/repo # <-- Change this to your repo path on EC2
            git pull
            sudo docker-compose pull || true
            sudo docker-compose up --build -d

# Required secrets:
#   EC2_HOST: Public IP or DNS of your EC2 instance
#   EC2_USER: SSH username (e.g., ubuntu)
#   EC2_SSH_KEY: Private SSH key for the user (use GitHub secrets) 